sbts/file/urls.py
from django.urls import path

from .views import BlobView, UploadView


app_name = 'file'
urlpatterns = [
    path('blobs/<uuid:key>/', BlobView.as_view(), name='blob'),
    path('blobs/', UploadView.as_view(), name='upload'),
]

sbts/page/urls.py
from django.urls import include, path
from sbts.page.views import TopPageView, FilePageView, TicketPageView, \
    LoginPageView, LogoutPageView, TicketView, TicketDetailPageView, \
    CommentView, FileView


app_name = 'page'
urlpatterns = [
    path('', TopPageView.as_view(), name='top_page'),
    path('file/', FilePageView.as_view(), name='file_page'),
    path('ticket/', TicketPageView.as_view(), name='ticket_page'),
    path('ticket/<uuid:key>/', TicketDetailPageView.as_view(), name='ticket_detail_page'),
    path('login/', LoginPageView.as_view(), name='login_page'),
    path('logout/', LogoutPageView.as_view(), name='logout_page'),
    path('api/page/files/', FileView.as_view(), name='file'),
    path('api/page/tickets/', TicketView.as_view(), name='ticket'),
    path('api/page/comments/', CommentView.as_view(), name='comment'),
    path('api/file/', include('sbts.file.urls')),
]

sbts/urls.py
from django.contrib import admin
from django.urls import include, path
from page.views import TopPageView, LoginPageView, LogoutPageView


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', TopPageView.as_view(), name='top'),
    path('login/', LoginPageView.as_view(), name='login'),
    path('logout/', LogoutPageView.as_view(), name='logout'),
    path('api/file/', include('file.urls')),
]

file/models.py
from django.db import models, transaction
import uuid
import boto3
import logging

from sbts.settings import S3_BUCKET_FILE, S3_ENDPOINT

logger = logging.getLogger(__name__)


class UploadedFile(models.Model):
    class Manager(models.Manager):
        def create_from_s3(self, key, username, name, last_modified, **kwargs):
            with transaction.atomic():
                uploader = S3Uploader.objects.get(
                    id=key,
                    status=S3Uploader.COMPLETED,
                    username=username)
                # S3のオブジェクトの所有者をS3UploaderからUploadedFileに移動
                file = self.create(
                    key=key,
                    name=name,
                    last_modified=last_modified,
                    size=uploader.size,
                    **kwargs)
                uploader.delete()

                return file

    class Meta:
        default_manager_name = 'objects'

    objects = Manager()

    key = models.UUIDField()
    name = models.CharField(max_length=255)
    last_modified = models.DateTimeField()
    size = models.BigIntegerField()


# 内部用
class S3Uploader(models.Model):
    COMPLETED = 0
    UPLOADING = 1
    STATUS_CHOICES = [
        (COMPLETED, 'Completed'),
        (UPLOADING, 'Uploading'),
    ]

    id = models.UUIDField(primary_key=True, editable=False, default=uuid.uuid4)
    status = models.IntegerField(choices=STATUS_CHOICES)
    size = models.BigIntegerField(default=-1)  # -1は未設定を表す
    username = models.CharField(max_length=150)

    @classmethod
    def upload(cls, file, username):
        key = uuid.uuid4()
        size = 0

        with transaction.atomic(durable=True):
            cls.objects.create(
                id=key,
                status=cls.UPLOADING,
                username=username)

        s3client = boto3.client('s3', endpoint_url=S3_ENDPOINT)

        resp = s3client.create_multipart_upload(
            Bucket=S3_BUCKET_FILE,
            Key=str(key))
        upload_id = resp['UploadId']

        multipart_upload = {
            'Parts': []
        }
        partnum = 1  # 1 ~ 10,000
        while chunk := file.read(8 * (1024 ** 2)):
            part = s3client.upload_part(
                Body=chunk,
                Bucket=S3_BUCKET_FILE,
                Key=str(key),
                PartNumber=partnum,
                UploadId=upload_id)
            multipart_upload['Parts'].append({
                'ETag': part['ETag'],
                'PartNumber': partnum,
            })
            partnum += 1
            size += len(chunk)

        # 空ファイルの場合
        if partnum == 1:
            part = s3client.upload_part(
                Body=b'',
                Bucket=S3_BUCKET_FILE,
                Key=str(key),
                PartNumber=partnum,
                UploadId=upload_id)
            multipart_upload['Parts'].append({
                'ETag': part['ETag'],
                'PartNumber': partnum,
            })

        s3client.complete_multipart_upload(
            Bucket=S3_BUCKET_FILE,
            Key=str(key),
            MultipartUpload=multipart_upload,
            UploadId=upload_id)

        with transaction.atomic(durable=True):
            uploader = cls.objects.get(id=key, status=cls.UPLOADING)
            uploader.status = cls.COMPLETED
            uploader.size = size
            uploader.save()

        return key


def upload_file(file, username):
    return S3Uploader.upload(file, username)

sbts/file/models.py
from django.conf import settings
from django.db import models, transaction
import uuid
import boto3

from sbts.core.models import CleanOpeManagerMixin, CleanOpeModelMixin


class UploadedFile(models.Model, CleanOpeModelMixin):
    class Manager(models.Manager, CleanOpeManagerMixin):
        def create_from_s3(self, key, username, filename, last_modified, **kwargs):
            with transaction.atomic():
                uploader = S3Uploader.objects.get(
                    key=key,
                    status=S3Uploader.COMPLETED,
                    size__isnull=False,
                    # 他のユーザーのブロブは参照できない
                    username=username)
                # S3のオブジェクトの所有者をS3UploaderからUploadedFileに移動
                file = self.create_cleanly(
                    key=key,
                    name=filename,
                    last_modified=last_modified,
                    size=uploader.size,
                    username=username,
                    **kwargs)
                uploader.delete()

                return file

    class Meta:
        default_manager_name = 'objects'

    objects = Manager()

    key = models.UUIDField(primary_key=True, default=uuid.uuid4)
    name = models.CharField(max_length=255)
    last_modified = models.DateTimeField()
    size = models.BigIntegerField()
    username = models.CharField(max_length=150)


# 内部用
class S3Uploader(models.Model, CleanOpeModelMixin):
    class Manager(models.Manager, CleanOpeManagerMixin):
        pass

    class Meta:
        default_manager_name = 'objects'

    objects = Manager()

    COMPLETED = 0
    UPLOADING = 1
    STATUS_CHOICES = [
        (COMPLETED, 'Completed'),
        (UPLOADING, 'Uploading'),
    ]

    key = models.UUIDField(primary_key=True, default=uuid.uuid4)
    status = models.IntegerField(choices=STATUS_CHOICES)
    size = models.BigIntegerField(null=True, blank=True, default=None)
    username = models.CharField(max_length=150)

    @classmethod
    def upload(cls, blob, username):
        key = uuid.uuid4()
        size = 0

        with transaction.atomic(durable=True):
            cls.objects.create_cleanly(
                key=key,
                status=cls.UPLOADING,
                username=username)

        s3client = boto3.client('s3', endpoint_url=settings.S3_ENDPOINT)

        resp = s3client.create_multipart_upload(
            Bucket=settings.S3_BUCKET_FILE,
            Key=str(key))
        upload_id = resp['UploadId']

        multipart_upload = {
            'Parts': []
        }
        partnum = 1  # 1 ~ 10,000
        while chunk := blob.read(settings.S3_CHUNK_SIZE):
            part = s3client.upload_part(
                Body=chunk,
                Bucket=settings.S3_BUCKET_FILE,
                Key=str(key),
                PartNumber=partnum,
                UploadId=upload_id)
            multipart_upload['Parts'].append({
                'ETag': part['ETag'],
                'PartNumber': partnum,
            })
            partnum += 1
            size += len(chunk)

        # 空ファイルの場合
        if partnum == 1:
            part = s3client.upload_part(
                Body=b'',
                Bucket=settings.S3_BUCKET_FILE,
                Key=str(key),
                PartNumber=partnum,
                UploadId=upload_id)
            multipart_upload['Parts'].append({
                'ETag': part['ETag'],
                'PartNumber': partnum,
            })

        s3client.complete_multipart_upload(
            Bucket=settings.S3_BUCKET_FILE,
            Key=str(key),
            MultipartUpload=multipart_upload,
            UploadId=upload_id)

        with transaction.atomic(durable=True):
            uploader = cls.objects.get(key=key, status=cls.UPLOADING)
            uploader.status = cls.COMPLETED
            uploader.size = size
            uploader.save_cleanly()

        return key


def upload_blob(blob, username):
    return S3Uploader.upload(blob, username)

sbts/ticket/models.py
from django.db import models

import uuid

from sbts.core.models import CleanOpeManagerMixin, CleanOpeModelMixin


class Ticket(models.Model, CleanOpeModelMixin):
    class Manager(models.Manager, CleanOpeManagerMixin):
        def sorted_tickets(self):
            return self.order_by('-created_at')

    class Meta:
        default_manager_name = 'objects'

    objects = Manager()

    key = models.UUIDField(primary_key=True, default=uuid.uuid4)
    title = models.CharField(max_length=255)
    created_at = models.DateTimeField()

    def sorted_comments(self):
        return self.comment_set.order_by('created_at')

    @property
    def lastmod(self):
        lastcommented_at = self.comment_set.aggregate(models.Max('created_at'))['created_at__max']
        if lastcommented_at is not None:
            return lastcommented_at
        return self.created_at


class Comment(models.Model, CleanOpeModelMixin):
    class Manager(models.Manager, CleanOpeManagerMixin):
        pass

    class Meta:
        default_manager_name = 'objects'

    objects = Manager()

    key = models.UUIDField(primary_key=True, default=uuid.uuid4)
    username = models.CharField(max_length=150)
    comment = models.CharField(max_length=65535)
    created_at = models.DateTimeField()
    ticket = models.ForeignKey(Ticket, on_delete=models.CASCADE)

file/views.py
from django.http import FileResponse
from django.utils import timezone
from django.views import View
from django.contrib.auth.mixins import LoginRequiredMixin
from rest_framework.parsers import BaseParser
from rest_framework.response import Response
from rest_framework.views import APIView

import boto3

from sbts.settings import S3_BUCKET_FILE, S3_ENDPOINT

from .models import UploadedFile, upload_file


class StreamParser(BaseParser):
    media_type = 'application/octet-stream'

    def parse(self, stream, media_type=None, parser_context=None):
        return stream


class StreamRequestView(APIView):
    parser_classes = [StreamParser]


class LoginRequiredView(LoginRequiredMixin, View):
    pass


class UploadView(StreamRequestView):
    def post(self, request, format=None):
        key = upload_file(request.data, request.user.username)
        return Response({'key': key})


class CreateView(APIView):
    def post(self, request, format=None):
        UploadedFile.objects.create_from_s3(
            key=request.data['key'],
            username=request.user.username,
            name=request.data['name'],
            last_modified=timezone.now())
        return Response({})


class BlobView(LoginRequiredView):
    def get(self, request, *args, **kwargs):
        fname = UploadedFile.objects.get(key=kwargs['key']).name
        s3client = boto3.client('s3', endpoint_url=S3_ENDPOINT)
        s3obj = s3client.get_object(Bucket=S3_BUCKET_FILE, Key=str(kwargs['key']))

        resp = FileResponse(
            s3obj['Body'],
            content_type='application/octet-stream',
            as_attachment=True,
            filename=fname,
        )
        resp['Content-Length'] = s3obj['ContentLength']
        return resp

sbts/file/views.py
from django.conf import settings
from django.core.exceptions import ObjectDoesNotExist
from django.http import FileResponse, Http404
from django.views import View
from rest_framework.parsers import BaseParser
from rest_framework.response import Response
from rest_framework.views import APIView

import boto3
import io

from .models import UploadedFile, upload_blob


class StreamParser(BaseParser):
    media_type = 'application/octet-stream'

    def parse(self, stream, media_type=None, parser_context=None):
        return {'blob': stream}


class StreamRequestView(APIView):
    parser_classes = [StreamParser]


class UploadView(StreamRequestView):
    def post(self, request, format=None):
        key = upload_blob(
            # HTTPリクエストのボディが空な場合、request.dataが空辞書に
            # なる
            request.data.get('blob', io.BytesIO(b'')),
            request.user.username)
        return Response({'key': key})


class BlobView(View):
    def get(self, request, *args, **kwargs):
        s3client = boto3.client('s3', endpoint_url=settings.S3_ENDPOINT)
        try:
            fname = UploadedFile.objects.get(key=kwargs['key']).name
            s3obj = s3client.get_object(
                Bucket=settings.S3_BUCKET_FILE,
                Key=str(kwargs['key']))
        except (ObjectDoesNotExist,
                s3client.exceptions.NoSuchKey,
                s3client.exceptions.InvalidObjectState):
            raise Http404()

        resp = FileResponse(
            s3obj['Body'],
            content_type='application/octet-stream',
            as_attachment=True,
            filename=fname,
        )
        resp['Content-Length'] = s3obj['ContentLength']
        return resp

sbts/page/templates/page/base.html
{% load static %}<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <link rel="stylesheet" href="{% static 'page/style.css' %}">
  <title>{% block title %}sbts{% endblock %}</title>
</head>
<body>
<header>
  <nav class="header-nav">
    <div class="header-top"><a href="{% url 'page:top_page' %}" ><b>sbts</b></a></div>

    <ul class="header-navlist">
      <li class="header-navtab{% if selected_tab == 'ticket' %} header-navtab-selected{% endif %}"><a href="{% url 'page:ticket_page' %}">チケット</a></li>
      <li class="header-navtab{% if selected_tab == 'file' %} header-navtab-selected{% endif %}"><a href="{% url 'page:file_page' %}">ファイル</a></li>
    </ul>

    <div class="header-authn">
      {% if user.is_authenticated %}
      <a href="{% url 'page:logout_page' %}">ログアウト</a>
      {% else %}
      <a href="{% url 'page:login_page' %}">ログイン</a>
      {% endif %}
    </div>
  </nav>
</header>
<div class="header-bottom"></div>
<main>{% block content %}
{% endblock %}  </main>
</body>
</html>

sbts/page/templates/page/file.html
{% extends 'page/base.html' %}
{% load static %}
{% load pretty_filters %}

{% block title %}ファイル - sbts{% endblock %}

{% block content %}
  {% if user.is_authenticated %}
  <form action="{% url 'page:file' %}" method="post" class="widget-group" id="uploadform">
    {% csrf_token %}
    <input type="hidden" name="blobkey">
    <input type="hidden" name="filename">
{% comment %}
      https://developer.mozilla.org/ja/docs/Web/API/File_API/Using_files_from_web_applications#click_%E3%83%A1%E3%82%BD%E3%83%83%E3%83%89%E3%82%92%E4%BD%BF%E7%94%A8%E3%81%97%E3%81%A6%E9%9D%9E%E8%A1%A8%E7%A4%BA%E3%81%AE_input_%E8%A6%81%E7%B4%A0%E3%82%92%E4%BD%BF%E7%94%A8%E3%81%99%E3%82%8B
{% endcomment %}
    <input type="file" style="display: none;" id="uploadfile">{# ファイルの中身はフォームで送信されない(REST APIで送信) #}
    <span class="enter-button"><button type="button" id="uploadbutton">＋アップロード</button></span>
  </form>
  {% endif %}

  <div class="file-list widget-group">
    <div class="file-list-header file-list-name"><b>名前</b></div>
    <div class="file-list-header file-list-username"><b>作成者</b></div>
    <div class="file-list-header file-list-lastmod"><b>作成日</b></div>
    <div class="file-list-header file-list-size"><b>大きさ</b></div>
    {% for file in file_list %}
    <div class="file-item file-list-name"><a href="{% url 'page:file:blob' file.key %}" title="{{ file.name }}">{{ file.name }}</a></div>
    <div class="file-item file-list-username"><span title="{{ file.username }}">{{ file.username }}</span></div>
    <div class="file-item file-list-lastmod"><span title="{{ file.last_modified }}">{{ file.last_modified }}</span></div>
    <div class="file-item file-list-size"><span title="{{ file.size|pretty_nbytes }}">{{ file.size|pretty_nbytes }}</span></div>
    {% endfor %}
  </div>

  {{ constant_map|json_script:"file-data" }}
  <script src="{% static 'page/file.js' %}"></script>
{% endblock %}

sbts/page/templates/page/login.html
{% extends 'page/base.html' %}
{% load static %}

{% block title %}ログイン - sbts{% endblock %}

{% block content %}
  {% if form.errors %}
  <p>パスワードが正しくありません。再度お試しください。</p>
  {% endif %}

  <form method="post" action="{% url 'page:login_page' %}" class="widget-group login-form">
    {% csrf_token %}

    <div class="login-group">
      <div class="login-label">ユーザーID</div>
      <div class="login-input">{{ form.username }}</div>
      <div class="login-label">パスワード</div>
      <div class="login-input">{{ form.password }}</div>
      <div class="login-enter enter-button"><input type="submit" value="ログイン"></div>
    </div>
    {% if next %}
    <input type="hidden" name="next" value="{{ next }}">
    {% endif %}
  </form>
{% endblock %}

sbts/page/templates/page/ticket.html
{% extends 'page/base.html' %}
{% load static %}

{% block title %}チケット - sbts{% endblock %}

{% block content %}
  {% if user.is_authenticated %}
  <form action="{% url 'page:ticket' %}" method="post" class="widget-group">
    {% csrf_token %}
    <input type="text" name="title" size="80" required>
    <span class="enter-button ticket-new"><input type="submit" value="チケットを作成"></span>
  </form>
  {% endif %}

  <div class="widget-group">
    {% for ticket in ticket_list %}
    <div class="ticket-item">
      <div><a href="{% url 'page:ticket_detail_page' ticket.key %}">{{ ticket.title }}</a></div>
      <div class="ticket-item-extra">{{ ticket.lastmod }}更新</div>
    </div>
    {% endfor %}
  </div>
{% endblock %}

sbts/page/templates/page/ticket_detail.html
{% extends 'page/base.html' %}
{% load static %}

{% block title %}{{ ticket.title }} - sbts{% endblock %}

{% block content %}
  <h1>{{ ticket.title }}</h1>
  <div class="widget-group">
    {% if comment_list %}
    {% for comment in comment_list %}
    <div id="comment-{{ comment.key }}" class="ticket-detail-item">
      <div class="ticket-detail-item-extra">{{ comment.username }} {{ comment.created_at }}</div>
      <div class="ticket-detail-comment">{{ comment.comment|urlize|linebreaksbr }}</div>
    </div>
    {% endfor %}
    {% else %}
    <p>コメントはまだありません。</p>
    {% endif %}
  </div>

  {% if user.is_authenticated %}
  <form action="{% url 'page:comment' %}" method="post" class="widget-group">
    {% csrf_token %}
    <input type="hidden" name="key" value="{{ ticket.key }}">
    <textarea rows="8" name="comment" required></textarea>
    <div class="enter-button"><input type="submit" value="コメント"></div>
  </form>
  {% endif %}
{% endblock %}

sbts/page/templates/page/top.html
{% extends 'page/base.html' %}

{% block content %}
  {{ text|urlize|linebreaks }}
{% endblock %}